name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install pyinstaller-versionfile
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
          install-only: true
    - name: Check UPX version
      run: upx --version
    - name: Create version.txt for PyInstaller
      working-directory: ./src
      run: create-version-file version.yml --outfile version.txt
    - name: PyInstaller Windows
      uses: aliencaocao/pyinstaller_action@main
      with:
        python_ver: '3.12'
        spec: 'src/main.spec'
        requirements: 'src/requirements.txt'
        upload_exe_with_name: 'Netease Cloudmusic Discord RPC.exe'
        clean_checkout: false
