name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install pyinstaller-versionfile
    - run: create-version-file src/version.yml --outfile src/version.txt
    - name: PyInstaller Windows
      uses: sayyid5416/pyinstaller@main
      with:
        python_ver: '3.11'
        spec: 'src/main.spec'
        requirements: 'src/requirements.txt'
        upload_exe_with_name: 'Netease Cloudmusic Discord RPC.exe'